repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest tests
        language: python
        additional_dependencies: [pre-commit, pytest]
        always_run: true
        pass_filenames: false