name: PyPI Package Version-Bump Workflow

# Trigger the workflow when a pull request is opened in the 'main' branch
on:
  pull_request:
    types: [opened]
    branches:
      - 'main'

# Specify permissions for the workflow
# This grants write access to the contents of the repository
permissions:
  contents: write

jobs:
  version-bump:
      runs-on: ubuntu-latest

      steps:
        # Checkout the project repository
        - name: Checkout repository
          uses: actions/checkout@v3 

        # Setup Python environment
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.8

        # Install dependencies
        - name: Install dependencies
          run: |
            pip install bumpversion

        # Bump Version
        # Run 'bumpversion patch' to increment the patch version
        # You can change 'patch' to 'major' or 'minor' based on the desired version bump
        - name: Bump Version
          run: | 
            bumpversion patch

        # Configure Git and commit changes
        - name: Configure Git and commit changes
          run: |
            git config --global user.name 'Automated Publishing Bot'
            git config --global user.email 'action@github.com'
            git fetch origin release:release
            git checkout release
            git add .
            git commit -am "Automated Commmit with Github Actions for Build & Version-Bump"
            git push origin release